name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - beta
          - nightly

    steps:
    - uses: actions/checkout@v3
      
    # Build
    - name: Build no features
      run: cargo build --verbose
#    - name: Build no features
#      run: cargo build --verbose --features regex
#
    # Test
    - name: Run tests no features
      run: cargo test --verbose --no-default-features
#    - name: Run tests with regex feature
#      run: cargo test --verbose --features regex
